/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Schnitzelbank_test.glb -o src/scene/Board.jsx -k

Panel meshes are adapted below: they stay invisible and take the pointer
so the poster can remain the surface the viewer sees.
*/

import { useEffect, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { useGraph, useThree } from "@react-three/fiber";
import * as THREE from "three";
import { HoverSelect } from "../components/HoverOutline.jsx";
import { isPanelName } from "../data/panels.js";

// The test panels sit on the poster's front face. Nudge them toward the
// camera so the outline reads as a visible edge instead of a hidden one.
const PANEL_OFFSET = [0.008, 0, 0];

function PanelHit({ node, hovered, onHoverPanel }) {
  return (
    <HoverSelect enabled={hovered}>
      <mesh
        name={node.name}
        geometry={node.geometry}
        position={PANEL_OFFSET}
        onPointerOver={(event) => {
          event.stopPropagation();
          onHoverPanel(node.name);
        }}
        onPointerOut={(event) => {
          event.stopPropagation();
          onHoverPanel((current) => (current === node.name ? null : current));
        }}
      >
        <meshBasicMaterial
          transparent
          opacity={0}
          depthWrite={false}
          colorWrite={false}
          side={THREE.DoubleSide}
        />
      </mesh>
    </HoverSelect>
  );
}

export function Model({ hoveredPanel = null, onHoverPanel = () => {}, ...props }) {
  const { scene } = useGLTF("/Schnitzelbank_test.glb");
  const { nodes } = useGraph(scene);
  const gl = useThree((state) => state.gl);
  const visuals = useMemo(
    () => Object.values(nodes).filter((node) => node.isMesh && !isPanelName(node.name)),
    [nodes],
  );
  const panels = useMemo(
    () => Object.values(nodes).filter((node) => node.isMesh && isPanelName(node.name)),
    [nodes],
  );

  useEffect(() => {
    const canvas = gl.domElement;
    const previous = canvas.style.cursor;
    canvas.style.cursor = hoveredPanel ? "pointer" : "default";
    return () => {
      canvas.style.cursor = previous;
    };
  }, [gl, hoveredPanel]);

  return (
    <group {...props} dispose={null}>
      {visuals.map((node) => (
        <mesh
          key={node.uuid}
          name={node.name}
          geometry={node.geometry}
          material={node.material}
          raycast={() => null}
        />
      ))}
      {panels.map((node) => (
        <PanelHit
          key={node.uuid}
          node={node}
          hovered={hoveredPanel === node.name}
          onHoverPanel={onHoverPanel}
        />
      ))}
    </group>
  );
}

useGLTF.preload("/Schnitzelbank_test.glb");

export default Model;
